# "agkozak/agkozak-zsh-prompt"
AGKOZAK_MULTILINE=0
AGKOZAK_LEFT_PROMPT_ONLY=1
AGKOZAK_PROMPT_DIRTRIM=2
AGKOZAK_BLANK_LINES=1
AGKOZAK_SHOW_STASH=1
AGKOZAK_SHOW_BG=1
AGKOZAK_BG_STRING='j'

AGKOZAK_COLORS_EXIT_STATUS=red
AGKOZAK_COLORS_USER_HOST=green
AGKOZAK_COLORS_PATH=blue
AGKOZAK_COLORS_BRANCH_STATUS=yellow
AGKOZAK_COLORS_PROMPT_CHAR=white      # Default text color
AGKOZAK_COLORS_CMD_EXEC_TIME=gray    # Default text color
AGKOZAK_COLORS_VIRTUALENV=green
AGKOZAK_COLORS_BG_STRING=magenta
